/**
 * Unified Lucide icon adapter.
 * Accepts legacy Remix/Iconify ids (`ri:...`) and Lucide names.
 * No emoji. One visual language across the CMS.
 */

import {
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Bell,
  Check,
  CheckCircle2,
  Circle,
  CircleHelp,
  Code2,
  Copy,
  DownloadCloud,
  ExternalLink,
  Eye,
  FilePlus2,
  FileText,
  FileUp,
  Filter,
  Flashlight,
  Flower2,
  Folder,
  FolderPlus,
  Grid2X2,
  Github,
  History,
  Home,
  Image,
  ImagePlus,
  Inbox,
  Info,
  LayoutDashboard,
  Link2,
  List,
  ListTree,
  Loader2,
  type LucideIcon,
  type LucideProps,
  MousePointer2,
  Music2,
  Newspaper,
  Palette,
  PenLine,
  Pin,
  Plus,
  PlusCircle,
  RefreshCw,
  Rocket,
  Rss,
  Route,
  Save,
  Search,
  Settings,
  Shield,
  SidebarOpen,
  SkipBack,
  SkipForward,
  Sparkles,
  Tag,
  Tags,
  Terminal,
  ToggleLeft,
  UploadCloud,
  UserRound,
  VolumeX,
  Wand2,
  X,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  // lucide native
  'layout-dashboard': LayoutDashboard,
  'file-text': FileText,
  image: Image,
  tag: Tag,
  palette: Palette,
  'wand-2': Wand2,
  settings: Settings,
  history: History,
  search: Search,
  plus: Plus,
  'plus-circle': PlusCircle,
  refresh: RefreshCw,
  'loader-2': Loader2,
  'alert-triangle': AlertTriangle,
  'check-circle-2': CheckCircle2,
  'circle-help': CircleHelp,
  'external-link': ExternalLink,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-down': ArrowDown,
  'arrow-up': ArrowUp,
  'arrow-up-down': ArrowUpDown,
  filter: Filter,
  folder: Folder,
  inbox: Inbox,
  archive: Archive,
  rocket: Rocket,
  sparkles: Sparkles,
  flower: Flower2,
  bell: Bell,
  save: Save,
  eye: Eye,
  info: Info,
  github: Github,
  link: Link2,
  music: Music2,
  terminal: Terminal,
  code: Code2,
  download: DownloadCloud,
  upload: UploadCloud,
  'file-up': FileUp,
  'image-plus': ImagePlus,
  pin: Pin,
  home: Home,
  user: UserRound,
  check: Check,
  x: X,
  circle: Circle,
  list: List,
  newspaper: Newspaper,
  shield: Shield,
  route: Route,
  toggle: ToggleLeft,
  flashlight: Flashlight,
  copy: Copy,
  draft: FileText,

  // legacy remix / iconify ids
  'ri:dashboard-3-line': LayoutDashboard,
  'ri:article-line': FileText,
  'ri:image-line': Image,
  'ri:image-2-line': Image,
  'ri:image-add-line': ImagePlus,
  'ri:price-tag-3-line': Tag,
  'ri:palette-line': Palette,
  'ri:magic-line': Wand2,
  'ri:settings-3-line': Settings,
  'ri:history-line': History,
  'ri:search-line': Search,
  'ri:add-line': Plus,
  'ri:add-circle-line': PlusCircle,
  'ri:refresh-line': RefreshCw,
  'ri:loader-4-line': Loader2,
  'ri:error-warning-line': AlertTriangle,
  'ri:checkbox-circle-line': CheckCircle2,
  'ri:checkbox-circle-fill': CheckCircle2,
  'ri:question-line': CircleHelp,
  'ri:flashlight-line': Flashlight,
  'ri:file-text-line': FileText,
  'ri:draft-line': FileText,
  'ri:file-upload-line': FileUp,
  'ri:file-list-3-line': List,
  'ri:file-copy-line': Copy,
  'ri:external-link-line': ExternalLink,
  'ri:arrow-right-line': ArrowRight,
  'ri:arrow-right-s-line': ArrowRight,
  'ri:arrow-left-line': ArrowLeft,
  'ri:arrow-left-s-line': ArrowLeft,
  'ri:arrow-down-s-line': ArrowDown,
  'ri:arrow-down-s-fill': ArrowDown,
  'ri:arrow-up-s-line': ArrowUp,
  'ri:arrow-up-s-fill': ArrowUp,
  'ri:arrow-up-down-line': ArrowUpDown,
  'ri:arrow-go-back-line': ArrowLeft,
  'ri:filter-3-line': Filter,
  'ri:filter-line': Filter,
  'ri:folder-line': Folder,
  'ri:folder-add-line': FolderPlus,
  'ri:inbox-2-line': Inbox,
  'ri:inbox-archive-line': Archive,
  'ri:archive-2-fill': Archive,
  'ri:rocket-line': Rocket,
  'ri:sparkling-line': Sparkles,
  'ri:flower-fill': Flower2,
  'ri:rss-line': Rss,
  'ri:quill-pen-ai-fill': PenLine,
  'ri:grid-fill': Grid2X2,
  'fa6-solid:tags': Tags,
  'ri:notification-3-line': Bell,
  'ri:save-line': Save,
  'ri:eye-line': Eye,
  'ri:information-line': Info,
  'ri:github-fill': Github,
  'ri:link': Link2,
  'ri:link-m': Link2,
  'ri:links-line': Link2,
  'ri:music-2-line': Music2,
  'ri:terminal-box-line': Terminal,
  'ri:code-line': Code2,
  'ri:code-box-line': Code2,
  'ri:code-s-slash-line': Code2,
  'ri:download-cloud-2-line': DownloadCloud,
  'ri:upload-cloud-2-line': UploadCloud,
  'ri:pushpin-line': Pin,
  'ri:pushpin-fill': Pin,
  'ri:home-heart-fill': Home,
  'fa6-regular:circle-user': UserRound,
  'ri:profile-line': UserRound,
  'ri:check-line': Check,
  'ri:close-line': X,
  'ri:circle-line': Circle,
  'ri:list-unordered': List,
  'ri:newspaper-line': Newspaper,
  'ri:shield-keyhole-line': Shield,
  'ri:route-line': Route,
  'ri:toggle-line': ToggleLeft,
  'ri:delete-bin-line': Archive,
  'ri:delete-bin-6-line': Archive,
  'ri:time-line': History,
  'ri:volume-mute-line': VolumeX,
  'ri:sidebar-unfold-line': SidebarOpen,
  'ri:skip-left-line': SkipBack,
  'ri:skip-right-line': SkipForward,
  'ri:node-tree': ListTree,
  'ri:bubble-chart-line': LayoutDashboard,
  'ri:cursor-line': MousePointer2,
  'ri:vscode-line': Code2,
  'ri:edit-line': FilePlus2,
};

export type AppIconName = keyof typeof ICON_MAP | string;

export interface AppIconProps extends Omit<LucideProps, 'ref'> {
  /** Lucide name or legacy `ri:...` id */
  name?: string;
  /** @deprecated use name; kept for drop-in Iconify compatibility */
  icon?: string;
}

function resolveIcon(raw?: string): LucideIcon {
  if (!raw) return Circle;
  if (ICON_MAP[raw]) return ICON_MAP[raw];
  const stripped = raw.replace(/^ri:/, '').replace(/-line$|-fill$|-2$/g, '');
  // try a few normalizations
  const candidates = [
    raw,
    stripped,
    stripped.replace(/-s$/, ''),
    raw.replace(/^lucide:/, ''),
  ];
  for (const key of candidates) {
    if (ICON_MAP[key]) return ICON_MAP[key];
  }
  return Circle;
}

export function AppIcon({ name, icon, className, strokeWidth = 1.75, ...props }: AppIconProps) {
  const Comp = resolveIcon(name || icon);
  return <Comp className={className} strokeWidth={strokeWidth} aria-hidden={props['aria-hidden'] ?? true} {...props} />;
}

/** Backward-compatible alias for gradual migration */
export const Icon = AppIcon;
