FROM node:22-alpine
WORKDIR /app/cms
RUN apk add --no-cache docker-cli docker-cli-compose
RUN npm i -g pnpm@9.15.1
COPY cms/package.json cms/pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY cms ./
EXPOSE 4322
CMD ["pnpm", "dev"]
